<a href="https://colab.research.google.com/github/ashirwadsangwan/Python/blob/master/PyTorch/00-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In computer programming, the stride of an array (also referred to as increment, pitch or step size) is the number of locations in memory between beginnings of successive array elements, measured in bytes or in units of the size of the array's elements. The stride cannot be smaller than the element size but can be larger, indicating extra space between elements.

In [0]:
def activation(x):
    
    '''
    This is Sigmoid activation function.
    
    Input : Tensor
    '''
    return 1/(1 + torch.exp(-x))

Now, we'll generate some random data to try our first neural network.

In [0]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [13]:
z = torch.sum(features * weights) + bias

y = activation(z)
print(y)

tensor([[0.1595]])


Or we can do the same calculation using `torch.mm` or `torch.matmul` which is used for matrix multiplication.

In [16]:
# z = torch.mm(features, weights) + bias
# y = activation(z)


# So this thing here gives us an error which says that we have size mismatch in the matrices.
# So, we'll reshape the weights matrix to be compatible with the size.

weights = weights.reshape(5,1)
z = torch.mm(features, weights) + bias
y = activation(z)

print(y)

tensor([[0.1595]])


Alternatively, we can do it like this

In [17]:
z = torch.mm(features, weights.view(5,1)) + bias
y = activation(z)
print(y)

tensor([[0.1595]])


Creating a multilayer network!

In [0]:
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

# weights for input layer

w1 = torch.randn(n_input, n_hidden)
b1 = torch.randn(1, n_hidden)

# weights for hidden layer to output layer

w2 = torch.randn(n_hidden, n_output)
b2 = torch.randn(1, n_output)

In [19]:
hidden = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(hidden, w2) + b2)

print(output)

tensor([[0.6282]])
