In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [23]:
x = torch.empty(5, 3)
print(x)

tensor([[1.4860e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [6.4530e-10, 8.2722e-10, 8.5418e+20],
        [1.6778e+22, 6.6021e-07, 2.7447e-06],
        [2.5958e-09, 1.6619e+22, 2.6249e-33]])


Construct a randomly initialized matrix:



In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5911, 0.3577, 0.3146],
        [0.0942, 0.9891, 0.3434],
        [0.2220, 0.6162, 0.8660],
        [0.0821, 0.0290, 0.2093],
        [0.4330, 0.5154, 0.1770]])


Construct a matrix filled zeros and of dtype long:



In [25]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [26]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [27]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5352,  0.1005,  0.8238],
        [-0.6128,  0.8451,  0.6448],
        [ 0.1566, -1.1523,  0.9896],
        [ 0.0339,  0.0087,  0.7161],
        [ 0.4461,  0.9630, -1.0120]])


Get its size:



In [28]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [29]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7837,  0.7961,  1.0071],
        [-0.0125,  0.9907,  1.3410],
        [ 0.5737, -0.7156,  1.1892],
        [ 0.1232,  0.8075,  0.9639],
        [ 0.8557,  1.4135, -0.4064]])


Addition: syntax 2



In [30]:
print(torch.add(x, y))

tensor([[ 1.7837,  0.7961,  1.0071],
        [-0.0125,  0.9907,  1.3410],
        [ 0.5737, -0.7156,  1.1892],
        [ 0.1232,  0.8075,  0.9639],
        [ 0.8557,  1.4135, -0.4064]])


Addition: providing an output tensor as argument



In [31]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7837,  0.7961,  1.0071],
        [-0.0125,  0.9907,  1.3410],
        [ 0.5737, -0.7156,  1.1892],
        [ 0.1232,  0.8075,  0.9639],
        [ 0.8557,  1.4135, -0.4064]])


Addition: in-place



In [32]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7837,  0.7961,  1.0071],
        [-0.0125,  0.9907,  1.3410],
        [ 0.5737, -0.7156,  1.1892],
        [ 0.1232,  0.8075,  0.9639],
        [ 0.8557,  1.4135, -0.4064]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [33]:
print(x[:, 1])

tensor([ 0.1005,  0.8451, -1.1523,  0.0087,  0.9630])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [34]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [35]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1141])
-0.1140875443816185


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [36]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [37]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [38]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [39]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [40]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.8859], device='cuda:0')
tensor([0.8859], dtype=torch.float64)
