<a href="https://colab.research.google.com/github/ashirwadsangwan/Python/blob/master/PyTorch/00-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In computer programming, the stride of an array (also referred to as increment, pitch or step size) is the number of locations in memory between beginnings of successive array elements, measured in bytes or in units of the size of the array's elements. The stride cannot be smaller than the element size but can be larger, indicating extra space between elements.

In [4]:
def activation(x):
    
    '''
    This is Sigmoid activation function.
    
    Input : Tensor
    '''
    return 1/(1 + torch.exp(-x))

Now, we'll generate some random data to try our first neural network.

In [5]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [6]:
z = torch.sum(features * weights) + bias

y = activation(z)
print(y)

tensor([[0.1595]])


Or we can do the same calculation using `torch.mm` or `torch.matmul` which is used for matrix multiplication.

In [7]:
# z = torch.mm(features, weights) + bias
# y = activation(z)


# So this thing here gives us an error which says that we have size mismatch in the matrices.
# So, we'll reshape the weights matrix to be compatible with the size.

weights = weights.reshape(5,1)
z = torch.mm(features, weights) + bias
y = activation(z)

print(y)

tensor([[0.1595]])


Alternatively, we can do it like this

In [8]:
z = torch.mm(features, weights.view(5,1)) + bias
y = activation(z)
print(y)

tensor([[0.1595]])


Creating a multilayer network!

In [9]:
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

# weights for input layer

w1 = torch.randn(n_input, n_hidden)
b1 = torch.randn(1, n_hidden)

# weights for hidden layer to output layer

w2 = torch.randn(n_hidden, n_output)
b2 = torch.randn(1, n_output)

In [10]:
hidden = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(hidden, w2) + b2)

print(output)

tensor([[0.6282]])


In [13]:
torch.arange(0,9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
torch.linspace(0, 9, 10).reshape(5, -1)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [20]:
torch.rand(4,3) # gives out random tensor

tensor([[0.9936, 0.4703, 0.1049],
        [0.5137, 0.2674, 0.4990],
        [0.7447, 0.7213, 0.4414],
        [0.5550, 0.6361, 0.1081]])

In [21]:
torch.randn(4, 3) # normally dist values as a tensor

tensor([[-0.9941, -0.9837, -1.2494],
        [-0.1883,  0.2827,  0.1305],
        [ 0.3303, -0.0773, -0.9224],
        [-1.8941,  1.0056, -0.6948]])

In [23]:
torch.randint(low=0, high=11, size=(4,4))  # high is exclusive here!!!

tensor([[ 2,  1, 10,  0],
        [ 9,  9,  3,  4],
        [ 4,  8,  0,  8],
        [ 9,  1,  8,  7]])

In [25]:
x = torch.zeros(2,3)
torch.rand_like(x) # takes input a tensor and gives a new tensor of random values with same shape as given tensor.

tensor([[0.5999, 0.2923, 0.8259],
        [0.2218, 0.6009, 0.3572]])

In [29]:
torch.manual_seed(17) # setting the seed lets you get the same results for reproducabilty of results.
torch.randn(2, 4)

tensor([[-1.4135,  0.2336,  0.0340,  0.3499],
        [-0.0145, -0.6124, -1.1835, -1.4831]])

 ### Tensor Operations

In [32]:
# indexing and slicing with tensors

x = torch.arange(6).reshape(3, -1)

In [35]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [33]:
x[1,1] # asking for the element on row 1 and col 1

tensor(3)

In [34]:
x[:, 1] # indexing for column

tensor([1, 3, 5])

In [36]:
x[:, 1:] # slicing for the column

tensor([[1],
        [3],
        [5]])

In [37]:
# view and reshape

x = torch.arange(10)

In [38]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# view works with the most recent data/

z = x.view(2, -1)
y = x.reshape(2, -1)
x[0] = 99

In [43]:
z

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [45]:
y

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [48]:
a = torch.arange(1,4)

b = torch.arange(4, 7)

In [51]:
a.mul(b)

tensor([ 4, 10, 18])

In [52]:
a # a doesn't change after using mul but it will after using mul_

tensor([1, 2, 3])

In [53]:
a.mul_(b)

tensor([ 4, 10, 18])

In [54]:
a # the multiplication got copied into a

tensor([ 4, 10, 18])

In [55]:
# dot product

a.dot(b)

tensor(174)

In [58]:
torch.manual_seed(17)
a = torch.randn(2, 4)
b = torch.randn(4, 3)
print(a)
print(b)
torch.mm(a, b)

tensor([[-1.4135,  0.2336,  0.0340,  0.3499],
        [-0.0145, -0.6124, -1.1835, -1.4831]])
tensor([[ 1.8004,  0.0096,  0.1534],
        [-2.6631, -1.4311, -0.5483],
        [ 0.3232, -0.4780,  1.5618],
        [-0.1298, -0.1335,  1.2740]])


tensor([[-3.2015, -0.4109,  0.1539],
        [ 1.4146,  1.6399, -3.4043]])